const tintColorLight = '#0a7ea4';
const tintColorDark = '#4dabff';

export const Colors = {
  light: {
    text: '#11181C',
    background: '#fff',
    cardBackground: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    headerBackground: '#fff',
    headerBorder: '#e0e0e0',
    cardBorder: '#FFD700',
    infoBackground: '#f7f7f7',
    statsBarBackground: '#fff',
    buttonBackground: '#f0f0f0',
    placeholderBackground: '#eaeaea',
    divider: '#e0e0e0',
    bookmarkActive: '#ff4757',
    bookmarkInactive: '#666',
    chatButtonBorder: '#25D366',
    chatButtonBackground: '#eaffea',
    chatButtonText: '#25D366',
    callButtonBackground: '#ffb300',
    callButtonText: '#fff',
    danger: '#ff4757',
    mutedText: '#666',
    secondaryText: '#888',
    detailsCardBorder: '#ffe066',
    warningBackground: '#FFF8E6',
    tagBackground: '#E7F3FE',
    tagText: '#0E56A8',
  },
  dark: {
    text: '#ECEDEE',
    background: '#121212',
    cardBackground: '#1e1e1e',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    headerBackground: '#1a1a1a',
    headerBorder: '#333',
    cardBorder: '#FFD700',
    infoBackground: '#252525',
    statsBarBackground: '#1a1a1a',
    buttonBackground: '#2a2a2a',
    placeholderBackground: '#2c2c2c',
    divider: '#333',
    bookmarkActive: '#ff4757',
    bookmarkInactive: '#9BA1A6',
    chatButtonBorder: '#1c8f49',
    chatButtonBackground: '#143624',
    chatButtonText: '#25D366',
    callButtonBackground: '#c28300',
    callButtonText: '#fff',
    danger: '#ff4757',
    mutedText: '#9a9a9a',
    secondaryText: '#aaa',
    detailsCardBorder: '#8f7500',
    warningBackground: '#3f3000',
    tagBackground: '#0e3a66',
    tagText: '#a7d2ff',
  },
};
