import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  closeButton: {
    padding: 4,
  },
  favoriteButton: {
    padding: 4,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 100,
  },
  companyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  companyImage: {
    width: 56,
    height: 56,
    borderRadius: 8,
    marginRight: 12,
  },
  companyImagePlaceholder: {
    width: 56,
    height: 56,
    borderRadius: 8,
    backgroundColor: '#eaeaea',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  companyImagePlaceholderText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#999',
  },
  companyInfo: {
    flex: 1,
  },
  companyTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  companyName: {
    fontSize: 14,
    color: '#111',
    fontWeight: 'bold',
    marginBottom: 2,
  },
  jobTitle: {
    fontSize: 13,
    fontWeight: '500',
    color: '#333',
    marginBottom: 2,
  },
  salaryText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#00a000',
  },
  verifiedBadge: {
    marginLeft: 4,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  tag: {
    backgroundColor: '#E7F3FE',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 8,
    marginBottom: 8,
  },
  tagText: {
    color: '#0E56A8',
    fontSize: 13,
    fontWeight: '500',
  },
  detailCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#ffe066',
  },
  detailCardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#14171A',
    marginBottom: 20,
  },
  detailGrid: {
    flexDirection: 'column',
    gap: 8,
  },
  detailGridRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  detailGridCol: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    padding: 8,
    minHeight: 56,
  },
  detailGridColEmpty: {
    flex: 1,
    minHeight: 56,
    marginRight: 8,
  },
  detailIconContainer: {
    width: 36,
    alignItems: 'center',
    marginRight: 8,
  },
  detailTextContainer: {
    flex: 1,
  },
  detailLabelSmall: {
    fontSize: 11,
    color: '#888',
    fontWeight: '500',
    marginBottom: 1,
  },
  detailValueSmall: {
    fontSize: 13,
    color: '#222',
    fontWeight: '700',
  },
  descriptionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#ffe066',
  },
  descriptionText: {
    fontSize: 15,
    lineHeight: 22,
    color: '#14171A',
  },
  warningCard: {
    backgroundColor: '#FFF8E6',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  warningHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  warningTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#14171A',
    marginLeft: 8,
  },
  warningText: {
    fontSize: 13,
    color: '#14171A',
    marginBottom: 8,
    lineHeight: 20,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E1E1E1',
    padding: 16,
    paddingBottom: Platform.OS === 'ios' ? 32 : 16,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 2,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  chatButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#eaffea',
    borderRadius: 6,
    paddingVertical: 8,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#25D366',
  },
  chatText: {
    color: '#25D366',
    fontWeight: '600',
    marginLeft: 6,
    fontSize: 15,
  },
  callButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffb300',
    borderRadius: 6,
    paddingVertical: 8,
  },
  callText: {
    color: '#fff',
    fontWeight: '600',
    marginLeft: 6,
    fontSize: 15,
  },
  moreDetailsCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    marginTop: 8,
    borderWidth: 1.5,
    borderColor: '#ffe066',
  },
  moreDetailsTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#111',
    marginBottom: 8,
  },
  moreDetailsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12, // more space for clarity
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  moreDetailsLabel: {
    fontSize: 15,
    color: '#111',
    fontWeight: 'bold',
    minWidth: 110,
    marginRight: 8,
  },
  moreDetailsValue: {
    fontSize: 13,
    color: '#333',
    fontWeight: '500',
    flex: 1,
    flexWrap: 'wrap',
    marginBottom: 2,
  },
  showMoreLess: {
    color: '#2E86DE',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 2,
    alignSelf: 'flex-start',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 8,
  },
  cardHeaderRowCenter: {
    height: 64,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 0,
  },
  cardHeaderArrow: {
    marginLeft: 8,
  },
  heroSection: {
    marginTop: 10,
    marginBottom: 16,
    paddingHorizontal: 0,
    paddingVertical: 0,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  heroTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#222',
    textAlign: 'left',
    lineHeight: 22,
    padding: 0,
    margin: 0,
  },
  expandableCard: {
    borderWidth: 1.5,
    borderColor: '#ffe066',
    borderRadius: 12,
    backgroundColor: '#fff',
    marginBottom: 16,
    marginTop: 0,
    padding: 0,
  },
  vacancyTagHeader: {
    backgroundColor: '#f0f0f0',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginTop: 6,
    marginBottom: 2,
  },
  vacancyTextHeader: {
    fontSize: 13,
    color: '#222',
    fontWeight: '500',
  },
  applicationsCountHeader: {
    fontSize: 12,
    color: '#aaa',
    marginTop: 0,
    marginBottom: 2,
    marginLeft: 2,
  },
  roleName: {
    fontSize: 13,
    color: '#555',
    fontWeight: '700',
    marginBottom: 2,
  },
  vacancyTagHero: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 2,
    gap: 12,
  },
  vacancyTextHero: {
    fontSize: 13,
    color: '#222',
    fontWeight: '500',
    backgroundColor: '#f0f0f0',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  applicationsCountHero: {
    fontSize: 12,
    color: '#aaa',
    marginLeft: 2,
  },
  applicationsCountBelowTags: {
    fontSize: 12,
    color: '#aaa',
    marginBottom: 8,
    marginLeft: 2,
  },
  categoryName: {
    fontSize: 13,
    color: '#888',
    fontWeight: '500',
    marginBottom: 2,
  },
});

export default styles; 